version = 0.1

[default.global.parameters]
stack_name = "damarrama-website"
region = "ap-southeast-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = "DomainName=damarrama.com"
